language: csharp
mono: none
sudo: false
dotnet: 2.2
dist: xenial


script:
  - dotnet build -c Release
  - dotnet test  -c Release --no-build
  - dotnet pack  -c Release --no-build -p:NoWarn=NU5105


deploy:


  - on:
      branch: master
    provider: script
    script:
      - dotnet nuget push **/*.nupkg -s https://api.nuget.org/v3/index.json -k $NUGET_API_KEY
    skip_cleanup: true


  - on:
      branch: develop
    provider: script
    script:
      - dotnet nuget push **/*.nupkg -s https://www.myget.org/F/nettopologysuite/api/v2/package -k $MYGET_API_KEY
    skip_cleanup: true

env:
  global:
  - secure: KpJduqa5g74WdST4MLZ5S3WMt5KChvXyBSVhqR2kYjnX9vb8T04Mh7Fs5EEoh8Hcm6x6cRUnhmln6mPf0w9lwfA3t2LL/WYhGUBta9kKWdHkicUVAkyeGQOJDxWVg7Tqx7Z1TRJsAJyjfwZCX4r1lIC9HemJA9OhY2yDsWcvugXuE53f8ruusbKDfK9J8HokywID2lR8rPcp4zAOXA7pLBsMY1hqj/q3ywB4pd9QDZLWLD0SsyfZFIlXbSKsIhyT/A5/LtV74UTlvLCh2ufCQ+URKYki72PdYCDtMrMgXSdU48U91ihO+vgBgmPunS27m7/6JCg4d4YT10d30j6sgpMGwMCQZJaNTi2IwPpn64X6AsoEgfqLMUudnTWhEYK8gZgAZLQb/7KIJP/kGWgwqODQhw0O/1uYUGOImPhKj0AwrcrFeFqxZBD2fUkdkJDXSwEKvX7hjpWXjGvtIgChexRoQ0KDxjMyqM3vuBkEVLTYngQ21TuAiPJlT3p26YP6hramM4B0uaklLjeIGBaxWTOUFecZAzB5THmeSjIKraktPzJs/V8khc0XcmjPHY4dSeo/NARpndZu0XUm98bvipTIt/QW8s9ZCb66z8+kN82IC/XUbzY9zSWLzOmu2bW9ihUYkwfGp1mF/FYrCsN5mNHTS/3N6uKFWGwRHg2gxLQ=
  - secure: PT05W3fSetaZxg0rA2jSt3/v5f/Gnn5PzyoQZT09TfGvBYG6chy4w9WsK/1SLsEOF/PVfQD5Js4D/7JKm5WsjsY+13XGCrfccmoZjGBlasSDTaptJMhuA/14yy270rfXLOn7TOR51ykMQ4BXpQz3pB5eDWMZGnxUyPXY2oq8tYFM4TXNCPgGdQxLf3KNRsOJr6bxmaQcogMdSzd6ILDcDBjJlukXMBwKjOdS76jcUdnjPlXlc2dDtLKXbWLb4mgnwlGG+VG9mxiqBRHcsU3qalxEjR7rTio+eVtvvKX6SAEu1vjMkfJKDQl7Cq3OI+rZ1sA13LpccdR8UBgJOKi4qYbhWgA7SssqiB38H2ENJNnI2RuLQDYvZeTrpk5MD9rmgGEPb1qaYItUpOk2X34R1JmWvNs4Nl3uR/dv3kO+TAecwprgRCRL6wwnZCdd1C6nIW8Fogx65UYhSgSvnxJEeRlDIyzuxe+HkGkMBKSVDO+qdDFi+kKkFqtWE/3B03UlhH0Zd8UxdS2CMlti4eSn17FX4e1mIJdHWaFswr3TuTfLKJsM89erhangjtAkUh/nkek5R8jeRpca5KYoaA1ECVn6iQP/KFK8LbKN8A3vnY097s/HbgZyKz1Le79tpJCVcf5TK64Gu+WfRl/vLgMuorO+ZAfDTHY15OZcxzhPV0c=
